import fetch from "node-fetch";
import pg from "pg";
// const dynastyRankings = require("./constants");
const { Pool } = pg;

const pool = new Pool({
  user: process.env.PG_USER,
  host: process.env.PG_HOST,
  database: process.env.PG_DB,
  password: process.env.PG_PASSWORD,
  port: 5432,
});

const dynastyRankings = [
  { name: "Justin Jefferson", value: "9999" },
  { name: "CeeDee Lamb", value: "9992" },
  { name: "Ja'Marr Chase", value: "9980" },
  { name: "Amon-Ra St. Brown", value: "9354" },
  { name: "Bijan Robinson", value: "9233" },
  { name: "Marvin Harrison Jr.", value: "8785" },
  { name: "Breece Hall", value: "8679" },
  { name: "Jahmyr Gibbs", value: "8361" },
  { name: "Puka Nacua", value: "8155" },
  { name: "Garrett Wilson", value: "7938" },
  { name: "Christian McCaffrey", value: "7845" },
  { name: "Josh Allen", value: "7750" },
  { name: "Sam LaPorta", value: "7724" },
  { name: "A.J. Brown", value: "7719" },
  { name: "Patrick Mahomes", value: "7700" },
  { name: "Malik Nabers", value: "7650" },
  { name: "C.J. Stroud", value: "7233" },
  { name: "Chris Olave", value: "7114" },
  { name: "Drake London", value: "7055" },
  { name: "Jonathan Taylor", value: "7027" },
  { name: "Tyreek Hill", value: "6978" },
  { name: "DeVonta Smith", value: "6945" },
  { name: "Rome Odunze", value: "6917" },
  { name: "Jaylen Waddle", value: "6879" },
  { name: "Brandon Aiyuk", value: "6854" },
  { name: "Lamar Jackson", value: "6812" },
  { name: "Jalen Hurts", value: "6712" },
  { name: "Brock Bowers", value: "6711" },
  { name: "Kyren Williams", value: "6702" },
  { name: "De'Von Achane", value: "6655" },
  { name: "Michael Pittman", value: "6600" },
  { name: "Trey McBride", value: "6582" },
  { name: "Anthony Richardson", value: "6567" },
  { name: "D.J. Moore", value: "6494" },
  { name: "Travis Etienne", value: "6493" },
  { name: "Tee Higgins", value: "6434" },
  { name: "Joe Burrow", value: "6433" },
  { name: "Nico Collins", value: "6424" },
  { name: "Saquon Barkley", value: "6346" },
  { name: "DK Metcalf", value: "6342" },
  { name: "Jordan Addison", value: "6339" },
  { name: "Zay Flowers", value: "6310" },
  { name: "Kyle Pitts", value: "6286" },
  { name: "Dalton Kincaid", value: "6277" },
  { name: "Justin Herbert", value: "6210" },
  { name: "Caleb Williams", value: "6192" },
  { name: "Tank Dell", value: "6183" },
  { name: "Kenneth Walker III", value: "6043" },
  { name: "Jaxon Smith-Njigba", value: "6004" },
  { name: "Jordan Love", value: "5957" },
  { name: "Mark Andrews", value: "5948" },
  { name: "T.J. Hockenson", value: "5906" },
  { name: "George Pickens", value: "5859" },
  { name: "Josh Jacobs", value: "5852" },
  { name: "James Cook", value: "5834" },
  { name: "Deebo Samuel", value: "5669" },
  { name: "Jayden Reed", value: "5637" },
  { name: "Rachaad White", value: "5621" },
  { name: "Brian Thomas Jr.", value: "5610" },
  { name: "Kyler Murray", value: "5578" },
  { name: "Isiah Pacheco", value: "5497" },
  { name: "Mike Evans", value: "5313" },
  { name: "Rashee Rice", value: "5232" },
  { name: "Davante Adams", value: "5189" },
  { name: "Jayden Daniels", value: "5147" },
  { name: "Trevor Lawrence", value: "5087" },
  { name: "Stefon Diggs", value: "5072" },
  { name: "Travis Kelce", value: "4966" },
  { name: "Cooper Kupp", value: "4874" },
  { name: "Christian Kirk", value: "4825" },
  { name: "Amari Cooper", value: "4810" },
  { name: "Jonathon Brooks", value: "4799" },
  { name: "D'Andre Swift", value: "4798" },
  { name: "Christian Watson", value: "4760" },
  { name: "Xavier Worthy", value: "4759" },
  { name: "Terry McLaurin", value: "4733" },
  { name: "Marquise Brown", value: "4722" },
  { name: "David Montgomery", value: "4707" },
  { name: "Adonai Mitchell", value: "4698" },
  { name: "Javonte Williams", value: "4671" },
  { name: "Joe Mixon", value: "4628" },
  { name: "Brock Purdy", value: "4627" },
  { name: "Tyjae Spears", value: "4617" },
  { name: "Chris Godwin", value: "4563" },
  { name: "Ladd McConkey", value: "4563" },
  { name: "Dak Prescott", value: "4556" },
  { name: "Diontae Johnson", value: "4456" },
  { name: "Tua Tagovailoa", value: "4436" },
  { name: "Najee Harris", value: "4431" },
  { name: "George Kittle", value: "4430" },
  { name: "David Njoku", value: "4417" },
  { name: "Drake Maye", value: "4401" },
  { name: "Derrick Henry", value: "4401" },
  { name: "Calvin Ridley", value: "4385" },
  { name: "Rhamondre Stevenson", value: "4310" },
  { name: "Trey Benson", value: "4309" },
  { name: "Josh Downs", value: "4295" },
  { name: "Troy Franklin", value: "4274" },
  { name: "Keenan Allen", value: "4251" },
  { name: "Alvin Kamara", value: "4249" },
  { name: "Zamir White", value: "4207" },
  { name: "Romeo Doubs", value: "4199" },
  { name: "Tony Pollard", value: "4187" },
  { name: "Brian Robinson", value: "4151" },
  { name: "Jameson Williams", value: "4104" },
  { name: "Zach Charbonnet", value: "4060" },
  { name: "Michael Mayer", value: "4055" },
  { name: "Jaylen Warren", value: "4047" },
  { name: "Jake Ferguson", value: "4046" },
  { name: "Evan Engram", value: "3955" },
  { name: "Jahan Dotson", value: "3929" },
  { name: "Blake Corum", value: "3912" },
  { name: "Cole Kmet", value: "3861" },
  { name: "Nick Chubb", value: "3837" },
  { name: "Kendre Miller", value: "3824" },
  { name: "James Conner", value: "3782" },
  { name: "Xavier Legette", value: "3726" },
  { name: "Pat Freiermuth", value: "3721" },
  { name: "Dalton Schultz", value: "3717" },
  { name: "Aaron Jones", value: "3706" },
  { name: "Jared Goff", value: "3646" },
  { name: "Khalil Shakir", value: "3644" },
  { name: "Luke Musgrave", value: "3643" },
  { name: "Jerry Jeudy", value: "3642" },
  { name: "Dontayvion Wicks", value: "3557" },
  { name: "Keon Coleman", value: "3545" },
  { name: "J.J. McCarthy", value: "3533" },
  { name: "Zack Moss", value: "3533" },
  { name: "Jakobi Meyers", value: "3470" },
  { name: "Quentin Johnston", value: "3413" },
  { name: "Dallas Goedert", value: "3389" },
  { name: "Chase Brown", value: "3388" },
  { name: "Marvin Mims", value: "3378" },
  { name: "Isaiah Likely", value: "3367" },
  { name: "Kirk Cousins", value: "3340" },
  { name: "Curtis Samuel", value: "3318" },
  { name: "Bryce Young", value: "3276" },
  { name: "Courtland Sutton", value: "3273" },
  { name: "Michael Wilson", value: "3270" },
  { name: "Raheem Mostert", value: "3214" },
  { name: "Gabriel Davis", value: "3190" },
  { name: "Keaton Mitchell", value: "3189" },
  { name: "Devin Singletary", value: "3177" },
  { name: "Austin Ekeler", value: "3176" },
  { name: "Justin Fields", value: "3173" },
  { name: "DeAndre Hopkins", value: "3157" },
  { name: "Braelon Allen", value: "3136" },
  { name: "Roschon Johnson", value: "3104" },
  { name: "Chuba Hubbard", value: "3102" },
  { name: "Josh Palmer", value: "3055" },
  { name: "Michael Penix Jr.", value: "3032" },
  { name: "Demario Douglas", value: "2994" },
  { name: "Jerome Ford", value: "2968" },
  { name: "Ricky Pearsall", value: "2967" },
  { name: "Mike Williams", value: "2915" },
  { name: "Rashid Shaheed", value: "2899" },
  { name: "Deshaun Watson", value: "2883" },
  { name: "Baker Mayfield", value: "2880" },
  { name: "Will Levis", value: "2820" },
  { name: "Roman Wilson", value: "2819" },
  { name: "Tucker Kraft", value: "2771" },
  { name: "Gus Edwards", value: "2767" },
  { name: "Tyler Lockett", value: "2753" },
  { name: "Darnell Mooney", value: "2708" },
  { name: "Jalin Hyatt", value: "2668" },
  { name: "Tyler Allgeier", value: "2667" },
  { name: "Wan'Dale Robinson", value: "2660" },
  { name: "Rashod Bateman", value: "2619" },
  { name: "Jaylen Wright", value: "2565" },
  { name: "Matthew Stafford", value: "2549" },
  { name: "MarShawn Lloyd", value: "2527" },
  { name: "Treylon Burks", value: "2519" },
  { name: "Khalil Herbert", value: "2512" },
  { name: "Ja'Lynn Polk", value: "2507" },
  { name: "Bo Nix", value: "2498" },
  { name: "Antonio Gibson", value: "2494" },
  { name: "J.K. Dobbins", value: "2488" },
  { name: "Jonathan Mingo", value: "2469" },
  { name: "Jaleel McLaughlin", value: "2453" },
  { name: "Cade Otton", value: "2387" },
  { name: "Tank Bigsby", value: "2373" },
  { name: "Chigoziem Okonkwo", value: "2344" },
  { name: "Elijah Moore", value: "2344" },
  { name: "Trey Palmer", value: "2331" },
  { name: "Rondale Moore", value: "2308" },
  { name: "Alec Pierce", value: "2283" },
  { name: "Malachi Corley", value: "2221" },
  { name: "Rico Dowdle", value: "2219" },
  { name: "Ja'Tavion Sanders", value: "2208" },
  { name: "Audric Estime", value: "2197" },
  { name: "Aaron Rodgers", value: "2188" },
  { name: "Greg Dulcich", value: "2175" },
  { name: "Dameon Pierce", value: "2175" },
  { name: "Ty Chandler", value: "2148" },
  { name: "Noah Fant", value: "2143" },
  { name: "Will Shipley", value: "2125" },
  { name: "Greg Dortch", value: "2082" },
  { name: "AJ Dillon", value: "2081" },
  { name: "Daniel Jones", value: "2074" },
  { name: "Bucky Irving", value: "2053" },
  { name: "Luke McCaffrey", value: "2051" },
  { name: "Brandin Cooks", value: "2047" },
  { name: "A.T. Perry", value: "2021" },
  { name: "Elijah Mitchell", value: "2003" },
  { name: "Miles Sanders", value: "1983" },
  { name: "Tyler Boyd", value: "1968" },
  { name: "Sam Howell", value: "1964" },
  { name: "Dawson Knox", value: "1897" },
  { name: "Geno Smith", value: "1896" },
  { name: "Russell Wilson", value: "1892" },
  { name: "Zay Jones", value: "1875" },
  { name: "Alexander Mattison", value: "1865" },
  { name: "Parker Washington", value: "1828" },
  { name: "Tutu Atwell", value: "1824" },
  { name: "Hunter Henry", value: "1819" },
  { name: "John Metchie", value: "1816" },
  { name: "Andrei Iosivas", value: "1813" },
  { name: "Luke Schoonmaker", value: "1793" },
  { name: "Adam Thielen", value: "1792" },
  { name: "Israel Abanikanda", value: "1789" },
  { name: "K.J. Osborn", value: "1780" },
  { name: "Kenneth Gainwell", value: "1774" },
  { name: "Kendrick Bourne", value: "1773" },
  { name: "Daniel Bellinger", value: "1762" },
  { name: "Noah Brown", value: "1739" },
  { name: "Chris Rodriguez", value: "1731" },
  { name: "Deuce Vaughn", value: "1704" },
  { name: "Devontez Walker", value: "1692" },
  { name: "Juwan Johnson", value: "1690" },
  { name: "Tre Tucker", value: "1677" },
  { name: "Skyy Moore", value: "1673" },
  { name: "Cedric Tillman", value: "1666" },
  { name: "Noah Gray", value: "1646" },
  { name: "Brenden Rice", value: "1643" },
  { name: "Evan Hull", value: "1640" },
  { name: "Mike Gesicki", value: "1638" },
  { name: "Ezekiel Elliott", value: "1612" },
  { name: "Jauan Jennings", value: "1607" },
  { name: "Clyde Edwards-Helaire", value: "1585" },
  { name: "Zach Evans", value: "1583" },
  { name: "Frank Gore Jr.", value: "1558" },
  { name: "Jonnu Smith", value: "1555" },
  { name: "Derek Carr", value: "1542" },
  { name: "Isaiah Spiller", value: "1538" },
  { name: "Darius Slayton", value: "1537" },
  { name: "Calvin Austin III", value: "1527" },
  { name: "Justice Hill", value: "1516" },
  { name: "Brevin Jordan", value: "1500" },
  { name: "Jalen McMillan", value: "1479" },
  { name: "Michael Carter", value: "1479" },
  { name: "Gardner Minshew", value: "1478" },
  { name: "Darnell Washington", value: "1473" },
  { name: "Javon Baker", value: "1468" },
  { name: "Bo Melton", value: "1460" },
  { name: "D'Onta Foreman", value: "1459" },
  { name: "Donovan Peoples-Jones", value: "1446" },
  { name: "D.J. Chark", value: "1422" },
  { name: "Josh Reynolds", value: "1409" },
  { name: "Jelani Woods", value: "1382" },
  { name: "Sean Tucker", value: "1376" },
  { name: "Tyquan Thornton", value: "1373" },
  { name: "Xavier Gipson", value: "1339" },
  { name: "Cam Akers", value: "1314" },
  { name: "Jalen Tolbert", value: "1308" },
  { name: "Isaiah Hodgins", value: "1275" },
  { name: "Darren Waller", value: "1272" },
  { name: "Emari Demercado", value: "1245" },
  { name: "Xavier Hutchinson", value: "1236" },
  { name: "Irv Smith", value: "1231" },
  { name: "Terrace Marshall", value: "1227" },
  { name: "Spencer Rattler", value: "1223" },
  { name: "Justyn Ross", value: "1218" },
  { name: "Tyler Higbee", value: "1208" },
  { name: "Tyler Scott", value: "1192" },
  { name: "Sam Darnold", value: "1190" },
  { name: "KJ Hamler", value: "1182" },
  { name: "DeWayne McBride", value: "1150" },
  { name: "Gerald Everett", value: "1144" },
  { name: "Kareem Hunt", value: "1135" },
  { name: "Aidan O'Connell", value: "1133" },
  { name: "Trey Lance", value: "1131" },
  { name: "Taysom Hill", value: "1116" },
  { name: "Jordan Mason", value: "1111" },
  { name: "Tyler Conklin", value: "1108" },
  { name: "Justin Shorter", value: "1098" },
  { name: "Chris Evans", value: "1096" },
  { name: "Davis Allen", value: "1083" },
  { name: "David Bell", value: "1078" },
  { name: "Jamaal Williams", value: "1068" },
  { name: "Kadarius Toney", value: "1060" },
  { name: "JuJu Smith-Schuster", value: "1056" },
  { name: "Malik Davis", value: "1052" },
  { name: "Demarcus Robinson", value: "1047" },
  { name: "Charlie Jones", value: "1031" },
  { name: "Jermaine Burton", value: "1027" },
  { name: "Jake Bobo", value: "1024" },
  { name: "Samaje Perine", value: "1015" },
  { name: "Cole Turner", value: "1000" },
  { name: "Eric Gray", value: "999" },
  { name: "Colby Parkinson", value: "962" },
  { name: "Jalen Guyton", value: "962" },
  { name: "Odell Beckham", value: "962" },
  { name: "Dyami Brown", value: "959" },
  { name: "Emanuel Wilson", value: "948" },
  { name: "Johnny Wilson", value: "921" },
  { name: "Zach Ertz", value: "920" },
  { name: "Donald Parham", value: "914" },
  { name: "Mecole Hardman", value: "913" },
  { name: "Joshua Kelley", value: "912" },
  { name: "Kyle Philips", value: "911" },
  { name: "Pierre Strong Jr.", value: "910" },
  { name: "Kayshon Boutte", value: "909" },
  { name: "Keaontay Ingram", value: "902" },
  { name: "Michael Gallup", value: "893" },
  { name: "Hendon Hooker", value: "892" },
  { name: "Tommy Tremble", value: "891" },
  { name: "Trayveon Williams", value: "889" },
  { name: "Jeffery Wilson", value: "884" },
  { name: "Ray Davis", value: "881" },
  { name: "Van Jefferson", value: "871" },
  { name: "Hayden Hurst", value: "852" },
  { name: "Derius Davis", value: "852" },
  { name: "Parris Campbell", value: "836" },
  { name: "Brenton Strange", value: "819" },
  { name: "Malik Washington", value: "817" },
  { name: "Justin Watson", value: "793" },
  { name: "Ronnie Rivers", value: "788" },
  { name: "Hunter Renfrow", value: "784" },
  { name: "Allen Lazard", value: "783" },
  { name: "Dalvin Cook", value: "780" },
  { name: "Devin Duvernay", value: "763" },
  { name: "Laviska Shenault", value: "754" },
  { name: "Will Dissly", value: "752" },
  { name: "Ronnie Bell", value: "744" },
  { name: "Zonovan Knight", value: "738" },
  { name: "Quez Watkins", value: "732" },
  { name: "Michael Thomas", value: "732" },
  { name: "Rakim Jarrett", value: "727" },
  { name: "Kenny Pickett", value: "725" },
  { name: "Ty Johnson", value: "714" },
  { name: "Denzel Mims", value: "708" },
  { name: "Jeremy Ruckert", value: "704" },
  { name: "Kylen Granson", value: "701" },
  { name: "Kenny McIntosh", value: "694" },
  { name: "Nyheim Hines", value: "690" },
  { name: "Deon Jackson", value: "689" },
  { name: "Trey Sermon", value: "683" },
  { name: "Ben Sinnott", value: "677" },
  { name: "Chris Brooks", value: "672" },
  { name: "Jerick McKinnon", value: "670" },
  { name: "Ben Skowronek", value: "668" },
  { name: "Jake Browning", value: "662" },
  { name: "Chris Brooks", value: "662" },
  { name: "Chase Edmonds", value: "656" },
  { name: "Foster Moreau", value: "655" },
  { name: "Kevin Harris", value: "649" },
  { name: "Elijah Higgins", value: "648" },
  { name: "Dorian Thompson-Robinson", value: "643" },
  { name: "Marquez Callaway", value: "643" },
  { name: "Harrison Bryant", value: "639" },
  { name: "Tyrion Davis-Price", value: "636" },
  { name: "Albert Okwuegbunam", value: "624" },
  { name: "Tyler Johnson", value: "622" },
  { name: "DeeJay Dallas", value: "622" },
  { name: "Hassan Haskins", value: "619" },
  { name: "Craig Reynolds", value: "619" },
  { name: "Mack Hollins", value: "618" },
  { name: "Tylan Wallace", value: "616" },
  { name: "Deneric Prince", value: "612" },
  { name: "Jacoby Brissett", value: "610" },
  { name: "Tim Patrick", value: "604" },
  { name: "Brock Wright", value: "594" },
  { name: "Olamide Zaccheaus", value: "589" },
  { name: "Scotty Miller", value: "587" },
  { name: "Salvon Ahmed", value: "585" },
  { name: "Nick Westbrook-Ikhine", value: "578" },
  { name: "Jameis Winston", value: "576" },
  { name: "D'Ernest Johnson", value: "576" },
  { name: "Cameron Latu", value: "572" },
  { name: "Desmond Ridder", value: "570" },
  { name: "Marquez Valdes-Scantling", value: "560" },
  { name: "Jalen Nailor", value: "555" },
  { name: "Zach Wilson", value: "553" },
  { name: "Anthony Schwartz", value: "553" },
  { name: "Adam Trautman", value: "548" },
  { name: "Malik Heath", value: "541" },
  { name: "Isaiah McKenzie", value: "527" },
  { name: "Deven Thompkins", value: "526" },
  { name: "Kene Nwangwu", value: "525" },
  { name: "Lil'Jordan Humphrey", value: "515" },
  { name: "Braxton Berrios", value: "514" },
  { name: "Eno Benjamin", value: "512" },
  { name: "Cordarrelle Patterson", value: "508" },
  { name: "Mac Jones", value: "503" },
  { name: "Jarrett Stidham", value: "498" },
  { name: "Tyler Badie", value: "497" },
  { name: "Cedrick Wilson", value: "491" },
  { name: "Raheem Blackshear", value: "490" },
  { name: "Julius Chestnut", value: "487" },
  { name: "Joshua Dobbs", value: "480" },
  { name: "Samori Toure", value: "480" },
  { name: "Drew Lock", value: "479" },
  { name: "Brandon Powell", value: "477" },
  { name: "Nelson Agholor", value: "475" },
  { name: "Ihmir Smith-Marsette", value: "474" },
  { name: "Jason Brownlee", value: "472" },
  { name: "KaVontae Turpin", value: "471" },
  { name: "Peyton Hendershot", value: "469" },
  { name: "Tyler Huntley", value: "464" },
  { name: "Danny Gray", value: "462" },
  { name: "Deonte Harty", value: "461" },
  { name: "Mo Alie-Cox", value: "460" },
  { name: "Hunter Long", value: "459" },
  { name: "John Bates", value: "458" },
  { name: "Andrew Ogletree", value: "457" },
  { name: "Myles Gaskin", value: "456" },
  { name: "Trenton Irwin", value: "447" },
  { name: "Bailey Zappe", value: "443" },
  { name: "Austin Hooper", value: "443" },
  { name: "Erik Ezukanma", value: "439" },
  { name: "Jalen Reagor", value: "430" },
  { name: "Durham Smythe", value: "428" },
  { name: "Cade Stover", value: "423" },
  { name: "Jacob Cowing", value: "423" },
  { name: "Equanimeous St. Brown", value: "422" },
  { name: "Robert Woods", value: "422" },
  { name: "Gary Brightwell", value: "419" },
  { name: "Drew Sample", value: "414" },
  { name: "Joe Flacco", value: "408" },
  { name: "Ke'Shawn Vaughn", value: "403" },
  { name: "Jordan Travis", value: "398" },
  { name: "Malik Willis", value: "391" },
  { name: "DeVante Parker", value: "387" },
  { name: "Richie James", value: "370" },
  { name: "Josh Oliver", value: "363" },
  { name: "Tanner Hudson", value: "354" },
  { name: "Bryce Ford-Wheaton", value: "352" },
  { name: "Ashton Dulin", value: "352" },
  { name: "Travis Homer", value: "327" },
  { name: "Sterling Shepard", value: "315" },
  { name: "Malik Cunningham", value: "303" },
  { name: "Charlie Kolar", value: "297" },
  { name: "James Robinson", value: "291" },
  { name: "Rashaad Penny", value: "288" },
  { name: "Jimmy Garoppolo", value: "258" },
  { name: "Jaren Hall", value: "257" },
  { name: "D'Wayne Eskridge", value: "256" },
  { name: "Davis Mills", value: "255" },
  { name: "Taylor Heinicke", value: "225" },
  { name: "Mason Rudolph", value: "224" },
  { name: "Ryan Tannehill", value: "211" },
  { name: "Tyson Bagent", value: "211" },
  { name: "Kyle Trask", value: "211" },
  { name: "Clayton Tune", value: "208" },
  { name: "Stetson Bennett", value: "191" },
  { name: "Tyrod Taylor", value: "173" },
  { name: "Mitchell Trubisky", value: "139" },
  { name: "David Moore", value: "135" },
  { name: "Mike White", value: "97" },
  { name: "Joe Milton", value: "95" },
  { name: "Carson Wentz", value: "41" },
  { name: "Marcus Mariota", value: "34" },
  { name: "Nick Mullens", value: "23" },
  { name: "Max Duggan", value: "20" },
];

// Function to fetch NFL players and update the database
async function updatePlayerStats(year = "2023") {
  console.log("Start Update Players Stats.");
  try {
    const response = await fetch(
      `https://api.sleeper.app/v1/stats/nfl/regular/${year}`
    );
    const stats = await response.json();
    const client = await pool.connect();
    try {
      await client.query("BEGIN");
      await client.query("DELETE FROM player_stats where year = $1", [year]);

      for (const playerId in stats) {
        const player = stats[playerId];
        await client.query(
          "INSERT INTO player_stats (player_id, pos_rank_half_ppr, gms_active, pts_half_ppr, year) VALUES ($1, $2, $3, $4, $5)",
          [
            playerId,
            player.pos_rank_half_ppr,
            player.gms_active,
            player.pts_half_ppr,
            year,
          ]
        );
      }
      console.log("Update Stats Complete.");
      // Commit transaction
      await client.query("COMMIT");
    } catch (err) {
      await client.query("ROLLBACK");
      throw err;
    } finally {
      client.release();
    }
  } catch (error) {
    console.error("Failed to update NFL stats:", error);
  }
}
// Function to fetch NFL players and update the database
async function updateNflPlayers() {
  console.log("Start Update Players.");
  try {
    const response = await fetch("https://api.sleeper.app/v1/players/nfl");
    const players = await response.json();
    // Assuming players is an object where each key is a player ID
    const client = await pool.connect();
    try {
      // Begin transaction
      await client.query("BEGIN");

      // Optionally, clear the table before inserting new data
      await client.query("DELETE FROM nfl_players");

      for (const playerId in players) {
        const player = players[playerId];
        // Modify the query based on the structure of the players object
        // and your table structure
        await client.query(
          "INSERT INTO nfl_players (id, first_name, last_name, position, team, active, years_exp) VALUES ($1, $2, $3, $4, $5, $6, $7)",
          [
            playerId,
            player.first_name,
            player.last_name,
            player.position,
            player.team,
            player.active,
            player.years_exp,
          ]
        );
      }
      console.log("Update Complete.");
      // Commit transaction
      await client.query("COMMIT");
    } catch (err) {
      await client.query("ROLLBACK");
      throw err;
    } finally {
      client.release();
    }
  } catch (error) {
    console.error("Failed to update NFL players:", error);
  }
}

const updateDynastyRankings = async () => {
  console.log("Start Update Dynasty Rankings.");
  try {
    // Assuming players is an object where each key is a player ID
    const client = await pool.connect();
    try {
      // Begin transaction
      await client.query("BEGIN");

      dynastyRankings.forEach(async (player) => {
        // Modify the query based on the structure of the players object
        // and your table structure
        await client.query(
          "INSERT INTO dynasty_rankings (name, value) VALUES ($1, $2) ON CONFLICT (name) DO UPDATE SET value = $2;",
          [player.name, player.value]
        );
      });
      console.log("Update Complete.");
      // Commit transaction
      await client.query("COMMIT");
    } catch (err) {
      await client.query("ROLLBACK");
      throw err;
    } finally {
      client.release();
    }
  } catch (error) {
    console.error("Failed to update Rankings:", error);
  }
};

export { updateNflPlayers, updatePlayerStats, updateDynastyRankings };
