import fetch from "node-fetch";
import pg from "pg";
// const dynastyRankings = require("./constants");
const { Pool } = pg;

const pool = new Pool({
  user: process.env.PG_USER,
  host: process.env.PG_HOST,
  database: process.env.PG_DB,
  password: process.env.PG_PASSWORD,
  port: 5432,
});

const dynastyRankings = [
  { name: "Justin Jefferson", value: "9999" },
  { name: "Ja'Marr Chase", value: "9999" },
  { name: "CeeDee Lamb", value: "9989" },
  { name: "Amon-Ra St. Brown", value: "9371" },
  { name: "Bijan Robinson", value: "9233" },
  { name: "Marvin Harrison Jr.", value: "8951" },
  { name: "Breece Hall", value: "8722" },
  { name: "Jahmyr Gibbs", value: "8321" },
  { name: "Puka Nacua", value: "8144" },
  { name: "Garrett Wilson", value: "7896" },
  { name: "Christian McCaffrey", value: "7806" },
  { name: "Sam LaPorta", value: "7775" },
  { name: "Patrick Mahomes", value: "7749" },
  { name: "A.J. Brown", value: "7735" },
  { name: "Josh Allen", value: "7732" },
  { name: "Malik Nabers", value: "7728" },
  { name: "C.J. Stroud", value: "7284" },
  { name: "Drake London", value: "7139" },
  { name: "Chris Olave", value: "7134" },
  { name: "Tyreek Hill", value: "7024" },
  { name: "Jonathan Taylor", value: "6976" },
  { name: "Brandon Aiyuk", value: "6967" },
  { name: "DeVonta Smith", value: "6900" },
  { name: "Rome Odunze", value: "6856" },
  { name: "Jaylen Waddle", value: "6846" },
  { name: "Lamar Jackson", value: "6791" },
  { name: "Jalen Hurts", value: "6741" },
  { name: "De'Von Achane", value: "6622" },
  { name: "D.J. Moore", value: "6555" },
  { name: "Travis Etienne", value: "6549" },
  { name: "Michael Pittman", value: "6546" },
  { name: "Jordan Addison", value: "6544" },
  { name: "Anthony Richardson", value: "6540" },
  { name: "Kyren Williams", value: "6520" },
  { name: "Trey McBride", value: "6468" },
  { name: "Tee Higgins", value: "6426" },
  { name: "Nico Collins", value: "6422" },
  { name: "Brock Bowers", value: "6400" },
  { name: "Joe Burrow", value: "6394" },
  { name: "Dalton Kincaid", value: "6344" },
  { name: "Saquon Barkley", value: "6322" },
  { name: "Zay Flowers", value: "6308" },
  { name: "DK Metcalf", value: "6292" },
  { name: "Tank Dell", value: "6271" },
  { name: "Caleb Williams", value: "6246" },
  { name: "Kyle Pitts", value: "6216" },
  { name: "Justin Herbert", value: "6211" },
  { name: "Kenneth Walker III", value: "6042" },
  { name: "Jaxon Smith-Njigba", value: "5967" },
  { name: "T.J. Hockenson", value: "5944" },
  { name: "Jordan Love", value: "5911" },
  { name: "Mark Andrews", value: "5886" },
  { name: "Josh Jacobs", value: "5852" },
  { name: "James Cook", value: "5751" },
  { name: "Brian Thomas Jr.", value: "5708" },
  { name: "George Pickens", value: "5704" },
  { name: "Kyler Murray", value: "5662" },
  { name: "Deebo Samuel", value: "5584" },
  { name: "Jayden Reed", value: "5561" },
  { name: "Rachaad White", value: "5558" },
  { name: "Xavier Worthy", value: "5527" },
  { name: "Isiah Pacheco", value: "5399" },
  { name: "Mike Evans", value: "5207" },
  { name: "Davante Adams", value: "5149" },
  { name: "Jayden Daniels", value: "5140" },
  { name: "Trevor Lawrence", value: "5124" },
  { name: "Rashee Rice", value: "5093" },
  { name: "Jonathon Brooks", value: "5010" },
  { name: "Stefon Diggs", value: "4933" },
  { name: "Ladd McConkey", value: "4932" },
  { name: "Cooper Kupp", value: "4893" },
  { name: "Travis Kelce", value: "4866" },
  { name: "Terry McLaurin", value: "4854" },
  { name: "Christian Kirk", value: "4751" },
  { name: "D'Andre Swift", value: "4739" },
  { name: "Marquise Brown", value: "4732" },
  { name: "Amari Cooper", value: "4724" },
  { name: "Javonte Williams", value: "4705" },
  { name: "Christian Watson", value: "4691" },
  { name: "Brock Purdy", value: "4665" },
  { name: "David Montgomery", value: "4584" },
  { name: "Adonai Mitchell", value: "4551" },
  { name: "Tyjae Spears", value: "4551" },
  { name: "Dak Prescott", value: "4537" },
  { name: "Joe Mixon", value: "4525" },
  { name: "Diontae Johnson", value: "4511" },
  { name: "Chris Godwin", value: "4450" },
  { name: "Trey Benson", value: "4427" },
  { name: "George Kittle", value: "4425" },
  { name: "Tua Tagovailoa", value: "4404" },
  { name: "Drake Maye", value: "4397" },
  { name: "Calvin Ridley", value: "4384" },
  { name: "Derrick Henry", value: "4374" },
  { name: "Najee Harris", value: "4345" },
  { name: "Josh Downs", value: "4254" },
  { name: "Rhamondre Stevenson", value: "4242" },
  { name: "Alvin Kamara", value: "4230" },
  { name: "David Njoku", value: "4221" },
  { name: "Zamir White", value: "4218" },
  { name: "Xavier Legette", value: "4207" },
  { name: "Xavier Legette", value: "4198" },
  { name: "Keenan Allen", value: "4168" },
  { name: "Brian Robinson", value: "4167" },
  { name: "Jaylen Warren", value: "4134" },
  { name: "Tony Pollard", value: "4106" },
  { name: "Jake Ferguson", value: "4081" },
  { name: "Zach Charbonnet", value: "4011" },
  { name: "Jameson Williams", value: "4000" },
  { name: "Evan Engram", value: "3985" },
  { name: "Keon Coleman", value: "3952" },
  { name: "Ricky Pearsall", value: "3936" },
  { name: "Jahan Dotson", value: "3916" },
  { name: "Blake Corum", value: "3885" },
  { name: "Troy Franklin", value: "3868" },
  { name: "Cole Kmet", value: "3839" },
  { name: "Kendre Miller", value: "3821" },
  { name: "J.J. McCarthy", value: "3764" },
  { name: "Nick Chubb", value: "3762" },
  { name: "Aaron Jones", value: "3706" },
  { name: "Dalton Schultz", value: "3681" },
  { name: "Pat Freiermuth", value: "3664" },
  { name: "Jared Goff", value: "3662" },
  { name: "James Conner", value: "3657" },
  { name: "Jerry Jeudy", value: "3641" },
  { name: "Khalil Shakir", value: "3612" },
  { name: "Luke Musgrave", value: "3583" },
  { name: "Dontayvion Wicks", value: "3554" },
  { name: "Jakobi Meyers", value: "3511" },
  { name: "Dallas Goedert", value: "3483" },
  { name: "Zack Moss", value: "3422" },
  { name: "Quentin Johnston", value: "3409" },
  { name: "Marvin Mims", value: "3404" },
  { name: "Isaiah Likely", value: "3394" },
  { name: "Courtland Sutton", value: "3347" },
  { name: "Kirk Cousins", value: "3346" },
  { name: "Chase Brown", value: "3329" },
  { name: "Keaton Mitchell", value: "3320" },
  { name: "DeAndre Hopkins", value: "3305" },
  { name: "Bryce Young", value: "3263" },
  { name: "Michael Wilson", value: "3231" },
  { name: "Michael Mayer", value: "3220" },
  { name: "Austin Ekeler", value: "3220" },
  { name: "Curtis Samuel", value: "3200" },
  { name: "Gabriel Davis", value: "3178" },
  { name: "Justin Fields", value: "3145" },
  { name: "Devin Singletary", value: "3138" },
  { name: "Raheem Mostert", value: "3131" },
  { name: "Roschon Johnson", value: "3114" },
  { name: "Braelon Allen", value: "3109" },
  { name: "Josh Palmer", value: "3091" },
  { name: "Michael Penix Jr.", value: "3047" },
  { name: "Demario Douglas", value: "3038" },
  { name: "Roman Wilson", value: "2984" },
  { name: "Rashid Shaheed", value: "2933" },
  { name: "Jerome Ford", value: "2929" },
  { name: "Deshaun Watson", value: "2925" },
  { name: "Chuba Hubbard", value: "2869" },
  { name: "Mike Williams", value: "2864" },
  { name: "Baker Mayfield", value: "2861" },
  { name: "Will Levis", value: "2852" },
  { name: "Rashod Bateman", value: "2774" },
  { name: "Ja'Lynn Polk", value: "2768" },
  { name: "Tyler Lockett", value: "2753" },
  { name: "Gus Edwards", value: "2704" },
  { name: "MarShawn Lloyd", value: "2677" },
  { name: "Wan'Dale Robinson", value: "2661" },
  { name: "Jaylen Wright", value: "2653" },
  { name: "Jalin Hyatt", value: "2653" },
  { name: "Tucker Kraft", value: "2643" },
  { name: "Darnell Mooney", value: "2612" },
  { name: "Tyler Allgeier", value: "2606" },
  { name: "J.K. Dobbins", value: "2589" },
  { name: "Matthew Stafford", value: "2540" },
  { name: "Bo Nix", value: "2537" },
  { name: "Jonathan Mingo", value: "2501" },
  { name: "Treylon Burks", value: "2441" },
  { name: "Antonio Gibson", value: "2441" },
  { name: "Khalil Herbert", value: "2429" },
  { name: "Chigoziem Okonkwo", value: "2421" },
  { name: "Tank Bigsby", value: "2409" },
  { name: "Jaleel McLaughlin", value: "2396" },
  { name: "Cade Otton", value: "2363" },
  { name: "Elijah Moore", value: "2306" },
  { name: "Trey Palmer", value: "2285" },
  { name: "Malachi Corley", value: "2276" },
  { name: "Rondale Moore", value: "2263" },
  { name: "Rico Dowdle", value: "2248" },
  { name: "Audric Estime", value: "2220" },
  { name: "Aaron Rodgers", value: "2216" },
  { name: "Alec Pierce", value: "2210" },
  { name: "Ja'Tavion Sanders", value: "2198" },
  { name: "Greg Dulcich", value: "2198" },
  { name: "Ty Chandler", value: "2191" },
  { name: "Luke McCaffrey", value: "2179" },
  { name: "Dameon Pierce", value: "2174" },
  { name: "Bucky Irving", value: "2120" },
  { name: "Daniel Jones", value: "2114" },
  { name: "Brandin Cooks", value: "2094" },
  { name: "Will Shipley", value: "2069" },
  { name: "Noah Fant", value: "2056" },
  { name: "Greg Dortch", value: "2046" },
  { name: "AJ Dillon", value: "2013" },
  { name: "Tyler Boyd", value: "2010" },
  { name: "Sam Howell", value: "1983" },
  { name: "A.T. Perry", value: "1977" },
  { name: "Elijah Mitchell", value: "1965" },
  { name: "Dawson Knox", value: "1933" },
  { name: "Geno Smith", value: "1908" },
  { name: "Kendrick Bourne", value: "1905" },
  { name: "Russell Wilson", value: "1889" },
  { name: "Miles Sanders", value: "1885" },
  { name: "Zay Jones", value: "1870" },
  { name: "Tutu Atwell", value: "1869" },
  { name: "John Metchie", value: "1863" },
  { name: "Daniel Bellinger", value: "1827" },
  { name: "Alexander Mattison", value: "1815" },
  { name: "Israel Abanikanda", value: "1788" },
  { name: "Chris Rodriguez", value: "1786" },
  { name: "Adam Thielen", value: "1783" },
  { name: "Luke Schoonmaker", value: "1776" },
  { name: "Andrei Iosivas", value: "1776" },
  { name: "Noah Brown", value: "1774" },
  { name: "Tre Tucker", value: "1772" },
  { name: "Parker Washington", value: "1749" },
  { name: "Kenneth Gainwell", value: "1744" },
  { name: "Hunter Henry", value: "1742" },
  { name: "K.J. Osborn", value: "1733" },
  { name: "Cedric Tillman", value: "1723" },
  { name: "Skyy Moore", value: "1713" },
  { name: "Devontez Walker", value: "1691" },
  { name: "Deuce Vaughn", value: "1686" },
  { name: "Brenden Rice", value: "1654" },
  { name: "Juwan Johnson", value: "1653" },
  { name: "Clyde Edwards-Helaire", value: "1649" },
  { name: "Evan Hull", value: "1619" },
  { name: "Noah Gray", value: "1609" },
  { name: "Ezekiel Elliott", value: "1598" },
  { name: "Mike Gesicki", value: "1596" },
  { name: "Frank Gore Jr.", value: "1591" },
  { name: "Jonnu Smith", value: "1561" },
  { name: "Zach Evans", value: "1558" },
  { name: "Derek Carr", value: "1548" },
  { name: "Isaiah Spiller", value: "1545" },
  { name: "Jauan Jennings", value: "1539" },
  { name: "D.J. Chark", value: "1525" },
  { name: "Justice Hill", value: "1524" },
  { name: "Calvin Austin III", value: "1518" },
  { name: "Jalen McMillan", value: "1506" },
  { name: "Darius Slayton", value: "1504" },
  { name: "Javon Baker", value: "1486" },
  { name: "Jelani Woods", value: "1474" },
  { name: "Gardner Minshew", value: "1471" },
  { name: "Donovan Peoples-Jones", value: "1463" },
  { name: "Darnell Washington", value: "1443" },
  { name: "Bo Melton", value: "1420" },
  { name: "Michael Carter", value: "1418" },
  { name: "Brevin Jordan", value: "1408" },
  { name: "Josh Reynolds", value: "1402" },
  { name: "Xavier Gipson", value: "1391" },
  { name: "Sean Tucker", value: "1380" },
  { name: "D'Onta Foreman", value: "1356" },
  { name: "Cam Akers", value: "1333" },
  { name: "Tyquan Thornton", value: "1326" },
  { name: "Jermaine Burton", value: "1297" },
  { name: "Xavier Hutchinson", value: "1287" },
  { name: "Darren Waller", value: "1283" },
  { name: "Jalen Tolbert", value: "1280" },
  { name: "KJ Hamler", value: "1267" },
  { name: "Isaiah Hodgins", value: "1257" },
  { name: "Terrace Marshall", value: "1243" },
  { name: "Spencer Rattler", value: "1239" },
  { name: "Irv Smith", value: "1238" },
  { name: "Tyler Higbee", value: "1208" },
  { name: "Sam Darnold", value: "1196" },
  { name: "DeWayne McBride", value: "1179" },
  { name: "Emari Demercado", value: "1173" },
  { name: "Justin Shorter", value: "1157" },
  { name: "Aidan O'Connell", value: "1150" },
  { name: "Justyn Ross", value: "1137" },
  { name: "Taysom Hill", value: "1132" },
  { name: "Tyler Scott", value: "1115" },
  { name: "Kareem Hunt", value: "1107" },
  { name: "Jordan Mason", value: "1097" },
  { name: "Trey Lance", value: "1095" },
  { name: "Gerald Everett", value: "1094" },
  { name: "JuJu Smith-Schuster", value: "1094" },
  { name: "Malik Davis", value: "1094" },
  { name: "Kadarius Toney", value: "1091" },
  { name: "David Bell", value: "1079" },
  { name: "Chris Evans", value: "1079" },
  { name: "Davis Allen", value: "1060" },
  { name: "Tyler Conklin", value: "1046" },
  { name: "Jalen Guyton", value: "1044" },
  { name: "Jamaal Williams", value: "1021" },
  { name: "Demarcus Robinson", value: "1019" },
  { name: "Charlie Jones", value: "1005" },
  { name: "Ray Davis", value: "989" },
  { name: "Jake Bobo", value: "986" },
  { name: "Eric Gray", value: "981" },
  { name: "Cole Turner", value: "961" },
  { name: "Johnny Wilson", value: "953" },
  { name: "Odell Beckham", value: "945" },
  { name: "Colby Parkinson", value: "933" },
  { name: "Kyle Philips", value: "932" },
  { name: "Dyami Brown", value: "929" },
  { name: "Donald Parham", value: "928" },
  { name: "Joshua Kelley", value: "928" },
  { name: "Samaje Perine", value: "927" },
  { name: "Pierre Strong Jr.", value: "915" },
  { name: "Zach Ertz", value: "910" },
  { name: "Michael Gallup", value: "900" },
  { name: "Jeffery Wilson", value: "898" },
  { name: "Tommy Tremble", value: "893" },
  { name: "Kayshon Boutte", value: "884" },
  { name: "Hendon Hooker", value: "883" },
  { name: "Trayveon Williams", value: "881" },
  { name: "Van Jefferson", value: "881" },
  { name: "Keaontay Ingram", value: "866" },
  { name: "Ben Sinnott", value: "849" },
  { name: "Derius Davis", value: "846" },
  { name: "Emanuel Wilson", value: "840" },
  { name: "Parris Campbell", value: "836" },
  { name: "Hayden Hurst", value: "834" },
  { name: "Malik Washington", value: "826" },
  { name: "Mecole Hardman", value: "822" },
  { name: "Allen Lazard", value: "817" },
  { name: "Ronnie Bell", value: "808" },
  { name: "Brenton Strange", value: "797" },
  { name: "Ronnie Rivers", value: "783" },
  { name: "Justin Watson", value: "776" },
  { name: "Will Dissly", value: "775" },
  { name: "Devin Duvernay", value: "770" },
  { name: "Kenny McIntosh", value: "763" },
  { name: "Quez Watkins", value: "761" },
  { name: "Dalvin Cook", value: "757" },
  { name: "Rakim Jarrett", value: "751" },
  { name: "Kylen Granson", value: "746" },
  { name: "Denzel Mims", value: "731" },
  { name: "Michael Thomas", value: "729" },
  { name: "Hunter Renfrow", value: "727" },
  { name: "Zonovan Knight", value: "727" },
  { name: "Ty Johnson", value: "720" },
  { name: "Jeremy Ruckert", value: "714" },
  { name: "Laviska Shenault", value: "700" },
  { name: "Ben Skowronek", value: "700" },
  { name: "Kalif Raymond", value: "690" },
  { name: "Deon Jackson", value: "684" },
  { name: "Kenny Pickett", value: "681" },
  { name: "Jerick McKinnon", value: "681" },
  { name: "Kevin Harris", value: "672" },
  { name: "Kevin Harris", value: "667" },
  { name: "Brock Wright", value: "665" },
  { name: "Hassan Haskins", value: "659" },
  { name: "Jake Browning", value: "658" },
  { name: "Chase Edmonds", value: "656" },
  { name: "Tyrion Davis-Price", value: "653" },
  { name: "Jacoby Brissett", value: "646" },
  { name: "Nyheim Hines", value: "643" },
  { name: "Chris Brooks", value: "640" },
  { name: "DeeJay Dallas", value: "638" },
  { name: "Dorian Thompson-Robinson", value: "633" },
  { name: "Tyler Johnson", value: "628" },
  { name: "Tim Patrick", value: "618" },
  { name: "Elijah Higgins", value: "609" },
  { name: "Nick Westbrook-Ikhine", value: "609" },
  { name: "Mack Hollins", value: "603" },
  { name: "Marquez Callaway", value: "602" },
  { name: "Scotty Miller", value: "601" },
  { name: "Zach Wilson", value: "600" },
  { name: "Deneric Prince", value: "597" },
  { name: "Tylan Wallace", value: "597" },
  { name: "Harrison Bryant", value: "593" },
  { name: "D'Ernest Johnson", value: "587" },
  { name: "Cameron Latu", value: "586" },
  { name: "Salvon Ahmed", value: "585" },
  { name: "Albert Okwuegbunam", value: "581" },
  { name: "Olamide Zaccheaus", value: "578" },
  { name: "Craig Reynolds", value: "577" },
  { name: "Foster Moreau", value: "568" },
  { name: "Jameis Winston", value: "562" },
  { name: "Desmond Ridder", value: "561" },
  { name: "Malik Heath", value: "559" },
  { name: "Lil'Jordan Humphrey", value: "544" },
  { name: "Isaiah McKenzie", value: "541" },
  { name: "Adam Trautman", value: "540" },
  { name: "Marquez Valdes-Scantling", value: "539" },
  { name: "Anthony Schwartz", value: "535" },
  { name: "Tyler Badie", value: "524" },
  { name: "Deven Thompkins", value: "520" },
  { name: "Cedrick Wilson", value: "518" },
  { name: "Kene Nwangwu", value: "516" },
  { name: "Jalen Nailor", value: "512" },
  { name: "Peyton Hendershot", value: "505" },
  { name: "Mac Jones", value: "504" },
  { name: "Drew Lock", value: "502" },
  { name: "Jarrett Stidham", value: "496" },
  { name: "Braxton Berrios", value: "496" },
  { name: "Mo Alie-Cox", value: "495" },
  { name: "Jason Brownlee", value: "494" },
  { name: "Julius Chestnut", value: "494" },
  { name: "Ihmir Smith-Marsette", value: "494" },
  { name: "Eno Benjamin", value: "490" },
  { name: "Nelson Agholor", value: "487" },
  { name: "Brandon Powell", value: "484" },
  { name: "Tyler Huntley", value: "474" },
  { name: "Deonte Harty", value: "472" },
  { name: "KaVontae Turpin", value: "472" },
  { name: "Austin Hooper", value: "470" },
  { name: "Hunter Long", value: "468" },
  { name: "Cordarrelle Patterson", value: "459" },
  { name: "Joshua Dobbs", value: "451" },
  { name: "Robert Woods", value: "450" },
  { name: "Trenton Irwin", value: "440" },
  { name: "Danny Gray", value: "439" },
  { name: "Bailey Zappe", value: "434" },
  { name: "Erik Ezukanma", value: "431" },
  { name: "Jacob Cowing", value: "430" },
  { name: "Equanimeous St. Brown", value: "428" },
  { name: "John Bates", value: "426" },
  { name: "Raheem Blackshear", value: "426" },
  { name: "Myles Gaskin", value: "426" },
  { name: "Samori Toure", value: "421" },
  { name: "Jordan Travis", value: "414" },
  { name: "Malik Willis", value: "411" },
  { name: "Joe Flacco", value: "410" },
  { name: "Andrew Ogletree", value: "402" },
  { name: "Bryce Ford-Wheaton", value: "402" },
  { name: "Ke'Shawn Vaughn", value: "402" },
  { name: "Gary Brightwell", value: "402" },
  { name: "Richie James", value: "400" },
  { name: "Jalen Reagor", value: "400" },
  { name: "Durham Smythe", value: "399" },
  { name: "Josh Oliver", value: "396" },
  { name: "Drew Sample", value: "393" },
  { name: "Cade Stover", value: "374" },
  { name: "DeVante Parker", value: "354" },
  { name: "Sterling Shepard", value: "334" },
  { name: "Tanner Hudson", value: "317" },
  { name: "Charlie Kolar", value: "310" },
  { name: "James Robinson", value: "309" },
  { name: "Malik Cunningham", value: "291" },
  { name: "Jimmy Garoppolo", value: "270" },
  { name: "Jaren Hall", value: "259" },
  { name: "Davis Mills", value: "256" },
  { name: "Mason Rudolph", value: "244" },
  { name: "Ryan Tannehill", value: "235" },
  { name: "Tommy DeVito", value: "222" },
  { name: "Kyle Trask", value: "213" },
  { name: "Taylor Heinicke", value: "209" },
  { name: "Clayton Tune", value: "209" },
  { name: "Tyson Bagent", value: "207" },
  { name: "Stetson Bennett", value: "192" },
  { name: "Tyrod Taylor", value: "169" },
  { name: "Mitchell Trubisky", value: "140" },
  { name: "Mike White", value: "98" },
  { name: "Joe Milton", value: "96" },
  { name: "Theo Johnson", value: "71" },
  { name: "Carson Wentz", value: "42" },
  { name: "Erick All", value: "39" },
  { name: "Isaac Guerendo", value: "37" },
  { name: "Marcus Mariota", value: "35" },
  { name: "Nick Mullens", value: "35" },
  { name: "Jared Wiley", value: "30" },
  { name: "Max Duggan", value: "20" },
];

// Function to fetch NFL players and update the database
async function updatePlayerStats(year = "2023") {
  console.log("Start Update Players Stats.");
  try {
    const response = await fetch(
      `https://api.sleeper.app/v1/stats/nfl/regular/${year}`
    );
    const stats = await response.json();
    const client = await pool.connect();
    try {
      await client.query("BEGIN");
      await client.query("DELETE FROM player_stats where year = $1", [year]);

      for (const playerId in stats) {
        const player = stats[playerId];
        await client.query(
          "INSERT INTO player_stats (player_id, pos_rank_half_ppr, gms_active, pts_half_ppr, year) VALUES ($1, $2, $3, $4, $5)",
          [
            playerId,
            player.pos_rank_half_ppr,
            player.gms_active,
            player.pts_half_ppr,
            year,
          ]
        );
      }
      console.log("Update Stats Complete.");
      // Commit transaction
      await client.query("COMMIT");
    } catch (err) {
      await client.query("ROLLBACK");
      throw err;
    } finally {
      client.release();
    }
  } catch (error) {
    console.error("Failed to update NFL stats:", error);
  }
}
// Function to fetch NFL players and update the database
async function updateNflPlayers() {
  console.log("Start Update Players.");
  try {
    const response = await fetch("https://api.sleeper.app/v1/players/nfl");
    const players = await response.json();
    // Assuming players is an object where each key is a player ID
    const client = await pool.connect();
    try {
      // Begin transaction
      await client.query("BEGIN");

      // Optionally, clear the table before inserting new data
      await client.query("DELETE FROM nfl_players");

      for (const playerId in players) {
        const player = players[playerId];
        // Modify the query based on the structure of the players object
        // and your table structure
        await client.query(
          "INSERT INTO nfl_players (id, first_name, last_name, position, team, active, years_exp) VALUES ($1, $2, $3, $4, $5, $6, $7)",
          [
            playerId,
            player.first_name,
            player.last_name,
            player.position,
            player.team,
            player.active,
            player.years_exp,
          ]
        );
      }
      console.log("Update Complete.");
      // Commit transaction
      await client.query("COMMIT");
    } catch (err) {
      await client.query("ROLLBACK");
      throw err;
    } finally {
      client.release();
    }
  } catch (error) {
    console.error("Failed to update NFL players:", error);
  }
}

const updateDynastyRankings = async () => {
  console.log("Start Update Dynasty Rankings.");
  try {
    // Assuming players is an object where each key is a player ID
    const client = await pool.connect();
    try {
      // Begin transaction
      await client.query("BEGIN");

      dynastyRankings.forEach(async (player) => {
        // Modify the query based on the structure of the players object
        // and your table structure
        await client.query(
          "INSERT INTO dynasty_rankings (name, value) VALUES ($1, $2) ON CONFLICT (name) DO UPDATE SET value = $2;",
          [player.name, player.value]
        );
      });
      console.log("Update Complete.");
      // Commit transaction
      await client.query("COMMIT");
    } catch (err) {
      await client.query("ROLLBACK");
      throw err;
    } finally {
      client.release();
    }
  } catch (error) {
    console.error("Failed to update Rankings:", error);
  }
};

export { updateNflPlayers, updatePlayerStats, updateDynastyRankings };
