import { readFileSync, existsSync, statSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { applyEliteCurve } from "./calculations.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const CSV_PATH = join(__dirname, "..", "output", "keeper_values.csv");

let cache = null;
let cacheTime = 0;

/**
 * Parse the keeper_values.csv generated by keeper_value_model.py.
 * Returns a Map keyed by lowercase player_name for fast lookup.
 */
function loadKeeperValues() {
  if (!existsSync(CSV_PATH)) return null;

  const mtime = statSync(CSV_PATH).mtimeMs;
  if (cache && mtime <= cacheTime) return cache;

  const raw = readFileSync(CSV_PATH, "utf-8");
  const lines = raw.trim().split("\n");
  if (lines.length < 2) return null;

  const headers = lines[0].split(",").map((h) => h.trim());
  const map = new Map();

  for (let i = 1; i < lines.length; i++) {
    const values = lines[i].split(",").map((v) => v.trim());
    const row = {};
    headers.forEach((h, idx) => {
      row[h] = values[idx];
    });
    const name = row.player_name;
    if (name) {
      map.set(name.toLowerCase(), {
        keeper_value: parseFloat(row.keeper_value) || 0,
        longevity_score: parseFloat(row.longevity_score) || 0,
        scarcity_score: parseFloat(row.scarcity_score) || 0,
        durability_score: parseFloat(row.durability_score) || 0,
        current_value: parseFloat(row.current_value) || 0,
        projected_years_elite: parseInt(row.projected_years_elite) || 0,
        keeper_fantasy_points: parseFloat(row.fantasy_points) || 0,
        years_exp: parseInt(row.years_exp) || 0,
        age: parseInt(row.age) || null,
        games_played: parseInt(row.games_played) || 0,
      });
    }
  }

  cache = map;
  cacheTime = mtime;
  return map;
}

/**
 * Look up a single player's keeper value data by name.
 * Tries exact match first, then partial.
 */
export function lookupKeeperValue(playerName) {
  const map = loadKeeperValues();
  if (!map || !playerName) return null;

  const key = playerName.toLowerCase();
  if (map.has(key)) return map.get(key);

  // Partial match fallback
  for (const [name, data] of map) {
    if (name.includes(key) || key.includes(name)) return data;
  }
  return null;
}

/**
 * Enrich an array of player objects with keeper value fields.
 * Merges on full_name (from DB) -> player_name (from CSV).
 * Overrides bfbValue with the keeper model's composite score (scaled to 0–10000)
 * so the FE can use it everywhere it previously used KTC value.
 */
// Toggle: scale keeper model values to match KTC range so both systems sort together.
// Set to false to use raw keeper model scale (0-10000) instead.
const NORMALIZE_TO_KTC = true;

// Position discount applied to prospects (no keeper-model entry) before the
// elite curve runs. Heavier discount on QBs reflects rookie-QB bust rate.
const PROSPECT_DISCOUNTS = {
  QB: 0.5,
  RB: 0.9,
  WR: 0.75,
  TE: 0.9,
};

export function enrichWithKeeperValues(players) {
  const map = loadKeeperValues();
  if (!map) return players;

  // Find max KTC value from players to use as scale target
  let maxKtc = 0;
  if (NORMALIZE_TO_KTC) {
    for (const p of players) {
      const v = p.value ? Number(p.value) : 0;
      if (v > maxKtc) maxKtc = v;
    }
  }

  // Find actual max keeper_value for proper normalization
  let maxKeeperValue = 0;
  for (const [, entry] of map) {
    if (entry.keeper_value > maxKeeperValue)
      maxKeeperValue = entry.keeper_value;
  }
  if (maxKeeperValue === 0) maxKeeperValue = 1;

  // Pre-compute positional scoring ranks so low-volume players don't receive
  // inflated values driven by longevity/scarcity scores alone. In the same
  // pass, find the max position-discounted KTC across prospects — used to
  // normalize the elite curve so the top prospect anchors at full value.
  const posFpGroups = {};
  let maxProspectDiscounted = 0;
  for (const p of players) {
    const kv = lookupKeeperValue(p.full_name || p.player_name);
    if (!kv) {
      const ktc = p.value ? Number(p.value) : 0;
      if (ktc > 0) {
        const d = PROSPECT_DISCOUNTS[p.position] ?? 0.9;
        const v = ktc * d;
        if (v > maxProspectDiscounted) maxProspectDiscounted = v;
      }
      continue;
    }
    if (!p.position || !p.id) continue;
    if (!posFpGroups[p.position]) posFpGroups[p.position] = [];
    posFpGroups[p.position].push({ id: p.id, fp: kv.keeper_fantasy_points });
  }
  const posRankById = {};
  for (const entries of Object.values(posFpGroups)) {
    entries.sort((a, b) => b.fp - a.fp);
    entries.forEach((e, i) => { posRankById[e.id] = i + 1; });
  }

  return players.map((player) => {
    const name = player.full_name || player.player_name;
    if (!name) return player;

    // Use partial match to handle name suffixes (e.g., "Ollie Gordon" → "Ollie Gordon II")
    const kv = lookupKeeperValue(name);
    if (!kv) {
      // Prospects have no production data — apply position discount, then
      // run through the elite curve so top dynasty rookies hold value while
      // mid/late prospects compress sharply.
      const ktcValue = player.value ? Number(player.value) : 0;
      if (ktcValue > 0) {
        const discount = PROSPECT_DISCOUNTS[player.position] ?? 0.9;
        const discounted = ktcValue * discount;
        return {
          ...player,
          bfbValue: applyEliteCurve(discounted, maxProspectDiscounted),
        };
      }
      return player;
    }

    const subScores = {
      keeper_value: kv.keeper_value,
      longevity_score: kv.longevity_score,
      scarcity_score: kv.scarcity_score,
      durability_score: kv.durability_score,
      current_value: kv.current_value,
      projected_years_elite: kv.projected_years_elite,
      ...(kv.age != null ? { age: kv.age } : {}),
    };

    // Incoming rookies with 0 NFL games: discount KTC dynasty value
    // Keeps them visible for trade value but prevents 0-production players
    // from ranking above proven producers
    if (kv.years_exp === 0 && kv.games_played === 0) {
      const ktcValue = player.value ? Number(player.value) : 0;
      const discountedValue = Math.round(ktcValue * 0.3);
      return { ...player, bfbValue: discountedValue, ...subScores };
    }

    // 1st-year players: 20/80 blend of KTC and model value
    // Production-based keeper model dominates, KTC provides minor dynasty upside
    // Low producers (<100 fantasy pts) get additional discount — draft hype shouldn't
    // outrank proven veterans
    if (kv.years_exp <= 1) {
      const ktcValue = player.value ? Number(player.value) : 0;
      const modelValue =
        NORMALIZE_TO_KTC && maxKtc > 0
          ? Math.round((kv.keeper_value / maxKeeperValue) * maxKtc)
          : Math.round(kv.keeper_value * 10000);
      let blendedValue = Math.round(0.2 * ktcValue + 0.8 * modelValue);
      if (kv.keeper_fantasy_points < 100) {
        blendedValue = Math.round(blendedValue * 0.7);
      }
      return { ...player, bfbValue: blendedValue, ...subScores };
    }

    const rawValue = kv.keeper_value * 10000;
    // Scale keeper values into KTC range using actual max for full spread
    let bfbValue =
      NORMALIZE_TO_KTC && maxKtc > 0
        ? Math.round((kv.keeper_value / maxKeeperValue) * maxKtc)
        : Math.round(rawValue);

    // Smooth penalty for experienced players outside top-25 at their position.
    // The keeper model can inflate longevity/scarcity for low-volume players
    // (a WR45 with good age/team situation). Linear taper from rank 25 down
    // to a 0.4 floor at rank 50+ avoids one-rank cliff inversions while still
    // keeping low-volume vets out of inflated surplus suggestions.
    const posRank = posRankById[player.id] ?? 999;
    if (posRank > 25) {
      const penalty = Math.max(0.4, 1 - (posRank - 25) * 0.024);
      bfbValue = Math.round(bfbValue * penalty);
    }

    return {
      ...player,
      bfbValue,
      keeper_value: kv.keeper_value,
      longevity_score: kv.longevity_score,
      scarcity_score: kv.scarcity_score,
      durability_score: kv.durability_score,
      current_value: kv.current_value,
      projected_years_elite: kv.projected_years_elite,
    };
  });
}

/**
 * Check if keeper values CSV exists and return metadata.
 */
export function getKeeperValuesStatus() {
  if (!existsSync(CSV_PATH)) {
    return { available: false, path: CSV_PATH };
  }
  const stat = statSync(CSV_PATH);
  const map = loadKeeperValues();
  return {
    available: true,
    path: CSV_PATH,
    lastModified: stat.mtime.toISOString(),
    playerCount: map ? map.size : 0,
  };
}
