import { readFileSync, existsSync, statSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const CSV_PATH = join(__dirname, "..", "output", "keeper_values.csv");

let cache = null;
let cacheTime = 0;
const CACHE_TTL_MS = 5 * 60 * 1000; // 5 minutes

/**
 * Parse the keeper_values.csv generated by keeper_value_model.py.
 * Returns a Map keyed by lowercase player_name for fast lookup.
 */
function loadKeeperValues() {
  if (!existsSync(CSV_PATH)) return null;

  const mtime = statSync(CSV_PATH).mtimeMs;
  if (cache && mtime <= cacheTime) return cache;

  const raw = readFileSync(CSV_PATH, "utf-8");
  const lines = raw.trim().split("\n");
  if (lines.length < 2) return null;

  const headers = lines[0].split(",").map((h) => h.trim());
  const map = new Map();

  for (let i = 1; i < lines.length; i++) {
    const values = lines[i].split(",").map((v) => v.trim());
    const row = {};
    headers.forEach((h, idx) => {
      row[h] = values[idx];
    });
    const name = row.player_name;
    if (name) {
      map.set(name.toLowerCase(), {
        keeper_value: parseFloat(row.keeper_value) || 0,
        longevity_score: parseFloat(row.longevity_score) || 0,
        scarcity_score: parseFloat(row.scarcity_score) || 0,
        durability_score: parseFloat(row.durability_score) || 0,
        current_value: parseFloat(row.current_value) || 0,
        projected_years_elite: parseInt(row.projected_years_elite) || 0,
        keeper_fantasy_points: parseFloat(row.fantasy_points) || 0,
        years_exp: parseInt(row.years_exp) || 0,
        games_played: parseInt(row.games_played) || 0,
      });
    }
  }

  cache = map;
  cacheTime = mtime;
  return map;
}

/**
 * Look up a single player's keeper value data by name.
 * Tries exact match first, then partial.
 */
export function lookupKeeperValue(playerName) {
  const map = loadKeeperValues();
  if (!map || !playerName) return null;

  const key = playerName.toLowerCase();
  if (map.has(key)) return map.get(key);

  // Partial match fallback
  for (const [name, data] of map) {
    if (name.includes(key) || key.includes(name)) return data;
  }
  return null;
}

/**
 * Enrich an array of player objects with keeper value fields.
 * Merges on full_name (from DB) -> player_name (from CSV).
 * Overrides bfbValue with the keeper model's composite score (scaled to 0–10000)
 * so the FE can use it everywhere it previously used KTC value.
 */
// Toggle: scale keeper model values to match KTC range so both systems sort together.
// Set to false to use raw keeper model scale (0-10000) instead.
const NORMALIZE_TO_KTC = true;

export function enrichWithKeeperValues(players) {
  const map = loadKeeperValues();
  if (!map) return players;

  // Find max KTC value from players to use as scale target
  let maxKtc = 0;
  if (NORMALIZE_TO_KTC) {
    for (const p of players) {
      const v = p.value ? Number(p.value) : 0;
      if (v > maxKtc) maxKtc = v;
    }
  }

  return players.map((player) => {
    const name = player.full_name || player.player_name;
    if (!name) return player;

    const kv = map.get(name.toLowerCase());
    if (!kv) return player;

    const subScores = {
      keeper_value: kv.keeper_value,
      longevity_score: kv.longevity_score,
      scarcity_score: kv.scarcity_score,
      durability_score: kv.durability_score,
      current_value: kv.current_value,
      projected_years_elite: kv.projected_years_elite,
    };

    // Incoming rookies with 0 NFL games: keep KTC dynasty value
    if (kv.years_exp === 0 && kv.games_played === 0) {
      return { ...player, ...subScores };
    }

    // 1st-year players: 50/50 blend of KTC and model value
    if (kv.years_exp <= 1) {
      const ktcValue = player.value ? Number(player.value) : 0;
      const modelValue = NORMALIZE_TO_KTC && maxKtc > 0
        ? Math.round((kv.keeper_value / 1.0) * maxKtc)
        : Math.round(kv.keeper_value * 10000);
      const blendedValue = Math.round(0.5 * ktcValue + 0.5 * modelValue);
      return { ...player, bfbValue: blendedValue, ...subScores };
    }

    const rawValue = kv.keeper_value * 10000;
    // Scale keeper values into KTC range so both systems are comparable
    const bfbValue = NORMALIZE_TO_KTC && maxKtc > 0
      ? Math.round((kv.keeper_value / 1.0) * maxKtc)
      : Math.round(rawValue);

    return {
      ...player,
      bfbValue,
      keeper_value: kv.keeper_value,
      longevity_score: kv.longevity_score,
      scarcity_score: kv.scarcity_score,
      durability_score: kv.durability_score,
      current_value: kv.current_value,
      projected_years_elite: kv.projected_years_elite,
    };
  });
}

/**
 * Check if keeper values CSV exists and return metadata.
 */
export function getKeeperValuesStatus() {
  if (!existsSync(CSV_PATH)) {
    return { available: false, path: CSV_PATH };
  }
  const stat = statSync(CSV_PATH);
  const map = loadKeeperValues();
  return {
    available: true,
    path: CSV_PATH,
    lastModified: stat.mtime.toISOString(),
    playerCount: map ? map.size : 0,
  };
}
